import Revenue from '@/components/Revenue';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function page() {
  return (
    <div>
      <Revenue />
    </div>
  );
}

export default page;
