import Revenue from '@/components/Revenue';
import TransactionsTable from '@/components/TransactionsTable';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function page() {
  return (
    <>
      <Revenue />
      <TransactionsTable />
    </>
  );
}

export default page;
